const TEMAS = {
  clasico: {
    id: 'clasico',
    nombre: 'Clásico',
    descripcion: 'Morado principal del juego',
    fondo: '#312e81',
    primario: '#4F46E5',
    secundario: '#ec4899',
    tarjeta: '#ffffff',
    texto: '#1e293b',
    textoSuave: '#64748b',
    borde: '#c7d2fe',
    barraXp: '#f59e0b',
  },
  noche: {
    id: 'noche',
    nombre: 'Noche',
    descripcion: 'Oscuro, cómodo y elegante',
    fondo: '#0f172a',
    primario: '#38bdf8',
    secundario: '#818cf8',
    tarjeta: '#ffffff',
    texto: '#1e293b',
    textoSuave: '#64748b',
    borde: '#bae6fd',
    barraXp: '#38bdf8',
  },
  dulce: {
    id: 'dulce',
    nombre: 'Dulce',
    descripcion: 'Rosa, suave y brillante',
    fondo: '#831843',
    primario: '#ec4899',
    secundario: '#f59e0b',
    tarjeta: '#ffffff',
    texto: '#1e293b',
    textoSuave: '#64748b',
    borde: '#fbcfe8',
    barraXp: '#f59e0b',
  },
  bosque: {
    id: 'bosque',
    nombre: 'Bosque',
    descripcion: 'Verde, fresco y tranquilo',
    fondo: '#064e3b',
    primario: '#10b981',
    secundario: '#84cc16',
    tarjeta: '#ffffff',
    texto: '#1e293b',
    textoSuave: '#64748b',
    borde: '#bbf7d0',
    barraXp: '#84cc16',
  },
};

export default TEMAS;